# Generated by Django 4.1.2 on 2023-06-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.AutoField(db_column='idDirector', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre_pelicula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activo', models.IntegerField()),
                ('id_director', models.ForeignKey(db_column='idDirector', on_delete=django.db.models.deletion.CASCADE, to='peliculas.director')),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='peliculas.genero')),
            ],
        ),
    ]
