# Generated by Django 4.1.2 on 2023-06-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Pelicula',
        ),
    ]
