# Generated by Django 4.1.2 on 2023-06-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='precio',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.AutoField(db_column='idCarro', primary_key=True, serialize=False)),
                ('nombre_pelicula', models.ForeignKey(db_column='nombrePelicula', on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula')),
            ],
        ),
    ]
