# Generated by Django 4.1.2 on 2023-06-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_pelicula_precio_alter_pelicula_imagen_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
